### ISSUE TITLE
TopPostFragment

### ISSUE THREAD

**Issue by Saqibm128** [git-mad/Bitter#29]
The Top Post Fragment does not properly onPause or onResume.

**Comment by nareddyt** [comment]
It actually does work as expected. The reason you were seeing log messages for random fragments was because of the way the ViewPager works. When you select a tab, Android will resume not only the selected fragment, but also the fragment that is directly to it's left and right. When you swipe to a different fragment, Android will automatically resume a fragment that is directly next to it, and pause a fragment that is not within 1 tab away from the current fragment.

I changed the post adapter to actual show semi-real data from the post objects. You can actually see that the 3 fragments in the User Profile page are all sorted properly based on their comparators.
